name: Build

on:
  pull_request:
    branches: ['dev']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: setupNodeVersion
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0

      - name: Make .env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_JWT_SECRET: ${{ secrets.JWT_SECRET }}
          envkey_NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          
          file_name: .env
          fail_on_empty: false

      - name: Install dependencies
        run: yarn install

      - name: Run lint
        run: yarn lint

      - name: Run build
        run: yarn build
